In [1]:
# importing necessary libraries
import numpy as np

Dataset Preparation

In [2]:
# generate 50 data points with 2 features
np.random.seed(42)
X = np.random.randint(0, 50, size=(50, 2))

# create 3 classes based on different conditions
# Class 0: Sum of features <= 35, Class 1: 35 < Sum of features <= 60, Class 2: Sum of features > 60
y = np.zeros(50)
y[(X[:, 0] + X[:, 1] > 35) & (X[:, 0] + X[:, 1] <= 60)] = 1
y[X[:, 0] + X[:, 1] > 60] = 2

# combining the features and its class for each data point
Data = np.hstack((X, y.reshape(-1, 1)))

# initialize X0 vector for intercept term
c_ones = np.ones((len(Data), 1))
# combining X0 with other features of Data
data = np.hstack([c_ones, Data])
print(data)

# splitting into train and test data
data_train = data[:30]
data_test = data[30:]
data = data_train

# initialize number of classes and theta matrix
num_classes = int(np.max(y)+1)
theta = np.zeros((num_classes, len(Data[0])))

[[ 1. 38. 28.  2.]
 [ 1. 14. 42.  1.]
 [ 1.  7. 20.  0.]
 [ 1. 38. 18.  1.]
 [ 1. 22. 10.  0.]
 [ 1. 10. 23.  0.]
 [ 1. 35. 39.  2.]
 [ 1. 23.  2.  0.]
 [ 1. 21.  1.  0.]
 [ 1. 23. 43.  2.]
 [ 1. 29. 37.  2.]
 [ 1.  1. 20.  0.]
 [ 1. 32. 11.  1.]
 [ 1. 21. 43.  2.]
 [ 1. 24. 48.  2.]
 [ 1. 26. 41.  2.]
 [ 1. 27. 15.  1.]
 [ 1. 14. 46.  1.]
 [ 1. 43.  2.  1.]
 [ 1. 36.  6.  1.]
 [ 1. 20.  8.  0.]
 [ 1. 38. 17.  1.]
 [ 1.  3. 24.  0.]
 [ 1. 13. 49.  2.]
 [ 1.  8. 25.  0.]
 [ 1.  1. 19.  0.]
 [ 1. 27. 46.  2.]
 [ 1.  6. 43.  1.]
 [ 1.  7. 46.  1.]
 [ 1. 34. 13.  1.]
 [ 1. 16. 35.  1.]
 [ 1. 49. 39.  2.]
 [ 1.  3.  1.  0.]
 [ 1.  5. 41.  1.]
 [ 1.  3. 28.  0.]
 [ 1. 17. 25.  1.]
 [ 1. 43. 33.  2.]
 [ 1.  9. 35.  1.]
 [ 1. 13. 30.  1.]
 [ 1. 47. 14.  2.]
 [ 1.  7. 13.  0.]
 [ 1. 22. 39.  2.]
 [ 1. 20. 15.  0.]
 [ 1. 44. 17.  2.]
 [ 1. 46. 23.  2.]
 [ 1. 25. 24.  1.]
 [ 1. 44. 40.  2.]
 [ 1. 28. 14.  1.]
 [ 1. 44.  0.  1.]
 [ 1. 24.  6.  0.]]


In [3]:
# tune learning rate, difference in likelihood, and number of iteration for termination
learning_rate = 1e-4
error = 1e-5
iteration = 25000

 Gradient Ascent Algorithm

In [4]:
# function to compute sum of exponents
def sum_exp(X, maximum):
    summation = 0
    for thetai in theta:
        summation += np.exp(np.dot(X, thetai)-maximum)
    return summation

# function to compute maximum value for log_sum_exp trick
def maximumValue(X):
    maximum = 0
    for thetai in theta:
        if np.dot(X, thetai) > maximum:
            maximum = np.dot(X, thetai)
    return maximum

# likelihood function
def likelihood_fun():
    # function to compute log_sum_exp
    def log_sum_exp(X):
        maximum = maximumValue(X)
        return maximum + np.log(sum_exp(X, maximum))

    Ltheta = 0
    for Xc in data:
        X = Xc[:-1] # extract features from a data point
        c = Xc[-1] # extract class from a data point
        # computing likelihood
        Ltheta += (np.dot(X, theta[int(c)]) - log_sum_exp(X))
    return Ltheta

# gradient function
def gradient_fun():
    # function to compute probability of X being class 'a'
    def prob_a(X):
        maximum = maximumValue(X)
        return (np.exp(np.dot(X, theta[i])) / (np.exp(maximum) * sum_exp(X, maximum)))

    # indicator function
    def indicator(c):
        if c == i:
            return 1
        else:
            return 0

    gradient = np.empty((0, len(theta[0])))
    for i in range(len(theta)):
        gradient_a = np.zeros(len(theta[0]))
        for Xc in data:
            X = Xc[:-1] # extract features from a data point
            c = Xc[-1] # extract class from a data point
            # computing gradient with respect to class 'a'
            gradient_a += X * (indicator(c)-prob_a(X))
        # computing gradient as a whole
        gradient = np.vstack([gradient, gradient_a])
    return gradient

# core portion of gradient ascent algorithm
likelihood = 0
i = 0
while True:
    likelihood_old = likelihood
    # calling likelihood function
    likelihood = likelihood_fun()
    print(f"Likelihood: {likelihood}")
    # calling gradient function
    gradient = gradient_fun()
    # update theta matrix
    theta += learning_rate * gradient
    i += 1
    if (abs(likelihood_old - likelihood) < error) or (i == iteration): #termination criteria
        break
print(theta)

Streaming output truncated to the last 5000 lines.
Likelihood: -14.345330344192728
Likelihood: -14.345093502557512
Likelihood: -14.344856674768803
Likelihood: -14.344619860825048
Likelihood: -14.344383060724718
Likelihood: -14.344146274466267
Likelihood: -14.34390950204815
Likelihood: -14.343672743468826
Likelihood: -14.34343599872675
Likelihood: -14.343199267820394
Likelihood: -14.342962550748203
Likelihood: -14.342725847508639
Likelihood: -14.342489158100165
Likelihood: -14.342252482521237
Likelihood: -14.34201582077032
Likelihood: -14.341779172845872
Likelihood: -14.341542538746355
Likelihood: -14.341305918470228
Likelihood: -14.341069312015948
Likelihood: -14.340832719381984
Likelihood: -14.340596140566795
Likelihood: -14.340359575568844
Likelihood: -14.340123024386584
Likelihood: -14.33988648701849
Likelihood: -14.339649963463017
Likelihood: -14.339413453718628
Likelihood: -14.339176957783792
Likelihood: -14.338940475656969
Likelihood: -14.338704007336615
Likelihood: -14.338467552

Prediction

In [10]:
# function to predict a class
def prediction(x_user):
    # appending 1 in input for intercept theta
    x = np.append([1], x_user)
    probability = np.empty(0)
    maximum = maximumValue(x)
    for i in range(num_classes):
        p = np.exp(np.dot(x, theta[i])) / (np.exp(maximum) * sum_exp(x, maximum))
        # appending probability of all classes in an array
        probability = np.append(probability, p)
    # finding a class with the highest probability
    predicted_class = np.argmax(probability)
    return predicted_class

In [11]:
# computing accuracy of the classifier
predicted = np.empty(0)
for i in data_test[:,1:-1]:
    # calling prediction function for each test data point
    pred = prediction(i)
    # appending predicted class of all test data points in an array
    predicted = np.append(predicted, pred)
# computing total number of correct predictions
correct_predictions = np.sum(data_test[:,-1] == predicted)
# computing total number of predictions
total_predictions = len(predicted)
# computing accuracy
accuracy = correct_predictions / total_predictions
print(f"Accuracy: {accuracy*100}%")

Accuracy: 90.0%


In [12]:
# take input from user or initialize input for prediction
x_user = np.array([25, 5])
print(f"{x_user} belongs to class {prediction(x_user)}")

[25  5] belongs to class 0
